workspace:
    base: /go
    path: src/github.com/SierraSoftworks/chieftan-server

services:
    mongodb:
        image: mongo:3.2

pipeline:

    go:build:
        image: golang:1.6
        commands:
            - go get -u github.com/FiloSottile/gvt
            - gvt restore
            - go test (go list ./... | grep -v /vendor/)
            - "CGO_ENABLED=0 GOOS=linux go build -o ../bin/chieftan -a -installsuffix cgo -ldflags '-s -X main.version=${DRONE_TAG=v1.0.0}-${DRONE_BRANCH}.${DRONE_COMMIT:0:6}'"

    docker:
        repo: chieftan/server
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
            - "go"
        username: "${DOCKER_USERNAME}"
        password: "${DOCKER_PASSWORD}"
        email: "${DOCKER_EMAIL}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"