stages:
  - dependencies
  - build
  - test
  - release
  - deploy

variables:
  CHIEFTAN_SERVER: http://chieftan.farmtracksa.com
  PROJECT_URL: https://git.emss.co.za/chieftan/server

npm:install:
  stage: dependencies
  script:
    - npm install
  cache:
    paths:
      - node_modules
  artifacts:
    name: $CI_BUILD_REF-dependencies
    paths:
      - node_modules/

npm:build:
  stage: build
  dependencies:
    - npm:install
  script:
    - npm run build
  artifacts:
    name: $CI_BUILD_REF-app
    paths:
      - dist/
      - package.json

npm:test:
  stage: test
  dependencies:
    - npm:install
    - npm:build
  script:
    - npm test

gitlab:release:
  stage: release
  dependencies:
    - npm:install
    - npm:build
  script:
    - 'echo "Registering release task"'
    - 'TASK_DATA=$(printf ''{"vars": { "ARTIFACT_BUILD": "%s", "VERSION": "%s" }, "metadata": { "description": "Version %s of the Chieftan Server (Build %s)", "url": "%s/commit/$CI_BUILD_REF/builds" }}'' "$CI_BUILD_ID" "$CI_BUILD_REF" "$CI_BUILD_REF" "$CI_BUILD_ID" "$PROJECT_URL")'
    - 'curl -s -X POST -H "Content-Type: application/json" -d "$TASK_DATA" "$CHIEFTAN_SERVER/api/v1/action/576a2f5d43e507a01cb9feae/tasks"'
    - 'curl -s -X POST -H "Content-Type: application/json" -d "$TASK_DATA" "$CHIEFTAN_SERVER/api/v1/action/576a308c43e507a01cb9feaf/tasks"'
  artifacts:
    name: $CI_BUILD_REF
    paths:
      - dist/
      - node_modules
      - package.json